-- Adiciona coluna secao
ALTER TABLE checklist_itens ADD COLUMN IF NOT EXISTS secao text;

-- Insere os 80 itens usando CTE para resolver os IDs dos setores
WITH ids AS (
  SELECT nome, id FROM setores WHERE nome IN ('Atendimento', 'Cozinha', 'Bar')
)
INSERT INTO checklist_itens (setor_id, secao, descricao, ordem)
SELECT ids.id, v.secao, v.descricao, v.ordem
FROM (VALUES
  -- ATENDIMENTO
  ('Atendimento','Auditoria operacional do evento','Garçons devidamente uniformizados',1),
  ('Atendimento','Auditoria operacional do evento','Limpeza e recreação devidamente uniformizados',2),
  ('Atendimento','Auditoria operacional do evento','Quantia de extras do salão bate com a quantia autorizada',3),
  ('Atendimento','Auditoria operacional do evento','Pão servido na mesa antes do convidado chegar',4),
  ('Atendimento','Auditoria operacional do evento','Maître devidamente uniformizado',5),
  ('Atendimento','Auditoria operacional do evento','Briefing realizado com a equipe',6),
  ('Atendimento','Auditoria operacional do evento','Praças e funções bem divididas',7),
  ('Atendimento','Auditoria operacional do evento','Houve manutenção de mesa',8),
  ('Atendimento','Auditoria operacional do evento','O buffet está limpo',9),
  ('Atendimento','Auditoria operacional do evento','Ilha 100% montada antes do início do evento (quando houver)',10),
  ('Atendimento','Auditoria operacional do evento','O serviço de bebidas foi eficiente',11),
  ('Atendimento','Auditoria operacional do evento','Os banheiros estão limpos e abastecidos',12),
  ('Atendimento','Auditoria operacional do evento','Salão limpo',13),
  ('Atendimento','Auditoria operacional do evento','Houve garçom o tempo todo no salão',14),
  ('Atendimento','Auditoria operacional do evento','Os garçons seguiram os protocolos (postura, sorriso)',15),
  ('Atendimento','Auditoria operacional do evento','As bandejas de serviço estavam limpas',16),
  ('Atendimento','Auditoria operacional do evento','Nenhuma mesa sem atendimento por mais de 10 minutos',17),
  ('Atendimento','Auditoria operacional do evento','Garçons circulando o tempo todo',18),
  ('Atendimento','Auditoria operacional do evento','Checklist durante o evento foi feito',19),
  ('Atendimento','Pré-evento','Checklist foi feito',20),
  ('Atendimento','Pré-evento','Todos os itens do contrato estão disponíveis no salão',21),
  ('Atendimento','Pré-evento','O mobiliário está limpo',22),
  ('Atendimento','Pré-evento','O depósito está limpo e organizado',23),
  ('Atendimento','Pré-evento','O mise en place está correto e completo',24),
  ('Atendimento','Metas checklist','Extras da semana enviados até segunda 12:00 no padrão solicitado',25),
  ('Atendimento','Metas checklist','Escala da semana para aprovação enviada até terça 12:00',26),
  ('Atendimento','Metas checklist','Houve conferência do ponto dos colaboradores',27),
  ('Atendimento','Metas checklist','Houve entrega de atestados',28),
  ('Atendimento','Equipe','Cumprimento das escalas',29),
  ('Atendimento','Equipe','Comunicação de faltas e atestados',30),
  ('Atendimento','Equipe','Postura e trabalho em equipe',31),
  ('Atendimento','Equipe','Interesse em treinamentos',32),
  ('Atendimento','Equipe','Abertura a novos processos',33),
  -- COZINHA
  ('Cozinha','Durante o evento','Equipe de cozinha devidamente uniformizada',1),
  ('Cozinha','Durante o evento','Pratos saíram no tempo certo, sem atraso que afetasse o serviço',2),
  ('Cozinha','Durante o evento','Quantidade de pratos/porções bateu com a quantia de convidados contratada',3),
  ('Cozinha','Durante o evento','Chef ou líder devidamente uniformizado e presente durante o evento',4),
  ('Cozinha','Durante o evento','Briefing realizado com a equipe antes do início do evento',5),
  ('Cozinha','Durante o evento','Praças e funções da cozinha bem divididas',6),
  ('Cozinha','Durante o evento','Houve reposição de pratos no buffet sem gerar falta',7),
  ('Cozinha','Durante o evento','Apresentação dos pratos seguiu o padrão da ficha técnica',8),
  ('Cozinha','Durante o evento','Cozinha permaneceu organizada durante o serviço (sem acúmulo de louça/sujeira)',9),
  ('Cozinha','Durante o evento','Checklist durante o evento foi feito',10),
  ('Cozinha','Pré-evento','Checklist de pré-evento foi feito',11),
  ('Cozinha','Pré-evento','Todos os itens do cardápio contratado estavam disponíveis',12),
  ('Cozinha','Pré-evento','Mise en place da cozinha completo antes do início',13),
  ('Cozinha','Pré-evento','Câmaras e estoque organizados antes do evento',14),
  ('Cozinha','Pré-evento','Equipamentos testados e funcionando antes do início',15),
  ('Cozinha','Metas checklist','Extras da semana enviados até segunda 12:00 no padrão solicitado',16),
  ('Cozinha','Metas checklist','Escala da semana para aprovação enviada até terça 12:00',17),
  ('Cozinha','Metas checklist','Houve conferência do ponto dos colaboradores',18),
  ('Cozinha','Metas checklist','Houve entrega de atestados',19),
  ('Cozinha','Equipe','Cumprimento das escalas',20),
  ('Cozinha','Equipe','Comunicação de faltas e atestados',21),
  ('Cozinha','Equipe','Postura e trabalho em equipe',22),
  ('Cozinha','Equipe','Interesse em treinamentos',23),
  ('Cozinha','Equipe','Abertura a novos processos',24),
  -- BAR
  ('Bar','Durante o evento','Equipe do bar devidamente uniformizada',1),
  ('Bar','Durante o evento','Quantidade de bebidas/insumos bate com a quantia autorizada para o evento',2),
  ('Bar','Durante o evento','Líder de bar devidamente uniformizado e presente durante o evento',3),
  ('Bar','Durante o evento','Briefing realizado com a equipe antes do início do evento',4),
  ('Bar','Durante o evento','Postos e funções do bar bem divididos',5),
  ('Bar','Durante o evento','O serviço de bebidas foi eficiente, sem fila ou demora excessiva',6),
  ('Bar','Durante o evento','Drinks/coquetéis seguiram o padrão de receita estabelecido',7),
  ('Bar','Durante o evento','Bar permaneceu organizado e limpo durante todo o evento',8),
  ('Bar','Durante o evento','Equipe seguiu os protocolos de atendimento no balcão (postura, sorriso)',9),
  ('Bar','Durante o evento','Checklist durante o evento foi feito',10),
  ('Bar','Pré-evento','Checklist de pré-evento foi feito',11),
  ('Bar','Pré-evento','Todos os itens de bar do contrato estavam disponíveis',12),
  ('Bar','Pré-evento','Mise en place do bar completo antes do início (gelo, copos, insumos)',13),
  ('Bar','Pré-evento','Equipamentos do bar testados e funcionando antes do início',14),
  ('Bar','Metas checklist','Extras da semana enviados até segunda 12:00 no padrão solicitado',15),
  ('Bar','Metas checklist','Escala da semana para aprovação enviada até terça 12:00',16),
  ('Bar','Metas checklist','Houve conferência do ponto dos colaboradores',17),
  ('Bar','Metas checklist','Houve entrega de atestados',18),
  ('Bar','Equipe','Cumprimento das escalas',19),
  ('Bar','Equipe','Comunicação de faltas e atestados',20),
  ('Bar','Equipe','Postura e trabalho em equipe',21),
  ('Bar','Equipe','Interesse em treinamentos',22),
  ('Bar','Equipe','Abertura a novos processos',23)
) AS v(setor_nome, secao, descricao, ordem)
JOIN ids ON ids.nome = v.setor_nome;
